
title: Triangle Drawing Tool Documentation
description: Documentation for the Triangle Drawing Tool.
url: "https://github.com/GEORGEMUTALE/draw_triangle" 

baseurl: ""

exclude:
  - "README.md"
  - "LICENSE"

# Theme configuration
theme: jekyll-theme-primer


# Set the source and destination directories
source: docs
destination: docs/_site

# Permalinks configuration for consistent URLs
permalink: /:categories/:title/

# Collections (if needed, e.g., for documentation pages)
collections:
  docs:
    output: true

# Sass/CSS configuration
sass:
  style: compressed
