name: Release Triangle Drawing Tool with Static Linux Binary and GitHub Pages

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        target:
          - x86_64-unknown-linux-musl       # Linux (musl)
          - x86_64-pc-windows-msvc          # Windows
          - x86_64-apple-darwin             # macOS

    env:
      BINARY_NAME: triangle_draw

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross (Linux Only)
        if: runner.os == 'Linux'
        run: cargo install cross

      - name: Install Target for Cross Compilation
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            rustup target add ${{ matrix.target }}
          fi

      - name: Build Binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cross build --target ${{ matrix.target }} --release --verbose
          else
            cargo build --target ${{ matrix.target }} --release --verbose
          fi

      - name: Create Release Archive
        run: |
          mkdir -p release

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/
            zip -r ${{ matrix.target }}.zip release
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages Directory
        run: |
          mkdir -p docs
          echo "# Triangle Drawing Tool Documentation" > docs/index.md
          echo "This is a GitHub Pages site for the Triangle Drawing Tool." >> docs/index.md
          echo "## Features" >> docs/index.md
          echo "- Draw customizable triangles with any character." >> docs/index.md
          echo "- Supports command-line arguments for height and character." >> docs/index.md
          echo "## Installation" >> docs/index.md
          echo "1. Download the binary for your platform from the [Releases](../../releases) section." >> docs/index.md
          echo "2. Run the binary from your terminal." >> docs/index.md
          echo "## Usage" >> docs/index.md
          echo "\`\`\`bash" >> docs/index.md
          echo "./triangle-draw --height 5 --character '#'" >> docs/index.md
          echo "\`\`\`" >> docs/index.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CLI_APP }}
          publish_dir: docs/
