name: Release Triangle Drawing Tool with Static Linux Binary and GitHub Pages

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BINARY_NAME: triangle_draw 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross (Linux Only)
        run: cargo install cross

      - name: Install Target for Cross Compilation
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Binary
        run: |
          cross build --target x86_64-unknown-linux-musl --release --verbose

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-musl/release/$BINARY_NAME release/
          tar -czvf $BINARY_NAME.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_APP }}

  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docs Directory
        run: |
          mkdir -p docs
          echo "# Triangle Drawing Tool Documentation" > docs/index.md
          echo "This is a GitHub Pages site for the Triangle Drawing Tool." >> docs/index.md
          echo "## Features" >> docs/index.md
          echo "- Draw customizable triangles with any character." >> docs/index.md
          echo "- Supports command-line arguments for height and character." >> docs/index.md
          echo "## Installation" >> docs/index.md
          echo "1. Download the binary for your platform from the [Releases](../../releases) section." >> docs/index.md
          echo "2. Run the binary from your terminal." >> docs/index.md
          echo "## Usage" >> docs/index.md
          echo "\`\`\`bash" >> docs/index.md
          echo "./triangle_draw --height 5 --character '#'" >> docs/index.md
          echo "\`\`\`" >> docs/index.md
          
      - name: Create Assets Directory and Style File
        run: |
          mkdir -p docs/assets/css
          echo "body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }" > docs/assets/css/style.scss

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CLI_APP }}
          publish_dir: docs/
