name: Release binary file

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl       # Linux (musl)
          - aarch64-unknown-linux-musl      # ARM Linux (musl)

    env:
      BINARY_NAME: draw_triangle

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install Target for Cross Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Build with Cross
        run: cross build --target ${{ matrix.target }} --release --verbose

      - name: Create Release Archive
        run: |
          mkdir -p release

          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/
            zip -r ${{ matrix.target }}.zip release
          elif [[ "${{ matrix.target }}" == *"darwin"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_APP }}

  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docs Directory
        run: |
          mkdir -p docs
          echo "# Triangle Drawing Tool Documentation" > docs/index.md
          echo "This is a GitHub Pages site for the Triangle Drawing Tool." >> docs/index.md
          echo "## Features" >> docs/index.md
          echo "- Draw customizable triangles with any character." >> docs/index.md
          echo "- Supports command-line arguments for height and character." >> docs/index.md
          echo "## Installation" >> docs/index.md
          echo "1. Download the binary for your platform from the [Releases](../../releases) section." >> docs/index.md
          echo "2. Run the binary from your terminal." >> docs/index.md
          echo "## Usage" >> docs/index.md
          echo "\`\`\`bash" >> docs/index.md
          echo "./triangle_draw --height 5 --character '#'" >> docs/index.md
          echo "\`\`\`" >> docs/index.md
          
      - name: Create Assets Directory and Style File
        run: |
          mkdir -p docs/assets/css
          echo "body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }" > docs/assets/css/style.scss

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CLI_APP }}
          publish_dir: docs/
